server:
  port: 8080

spring:
  application:
    name: cloudgateway
  #Configuration for spring cloud gateway
  cloud:
    gateway:
      routes:
        - id: service1
          uri: http://localhost:8080
          predicates:
            - Path=/service1sa/**
        - id: service2
          uri: http://localhost:8082
          predicates:
            - Path=/service2/**

#Enable actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"



